Move efibootmgr command to separate script so it can be run on cloned devices.
votingworks/vxsuite-complete-system pull request #144
Opened 2022-03-04 22:36 UTC by umbernhard

2022-03-04 22:47 UTC, benadida requested changes
caught a couple of bugs by inspection, I think, but check me. Make sure this runs properly independently and as part of the calling script.

2022-03-04 22:47 UTC, benadida commented on config/admin-functions/lockdown.sh
>  part=$(cat /sys/class/block/$(basename $DEV)/partition)
gotta move these too, I think?

2022-03-04 22:47 UTC, benadida commented on config/admin-functions/show-vx-suite-admin-menu.sh
missing `;;` I think?

2022-03-04 22:49 UTC, umbernhard commented on config/admin-functions/lockdown.sh
>  part=$(cat /sys/class/block/$(basename $DEV)/partition)
ope, good call.

2022-03-04 22:49 UTC, umbernhard commented on config/admin-functions/show-vx-suite-admin-menu.sh
also good call.

2022-03-04 23:35 UTC, benadida approved these changes

2022-03-08 02:45 UTC, benadida commented
testing this on a real machine, and seeing a couple of issues:

- the lockdown script fails on first run... but error message disappears quickly so I don't have any more info yet, I'll see what I can find.
- the setup-boot-entry script doesn't work because it doesn't have the executable bit set.

2022-03-08 03:04 UTC, benadida commented
I tried ctrl-c'ing out of the menu and doing `sudo ./lockdown.sh` at the prompt as `vx-admin`, and that worked on the first try. Maybe there's something wrong when it's run from the menu? I'll keep trying for a more helpful repro.

2022-03-14 18:56 UTC, merged